dataset_directory: '/home/dylan/datasets/cifar_png/'
output_directory: '/tmp/'
model_type: 'feature_spread_classifier'
model_file: null
guide_model_file: '/home/dylan/trained_model_files/pytorch/adversarial_project/other_models/guide_classifier.pt'
model_name: 'feature_spread_classifier'
number_epochs: 20
batch_size: 64
input_dimensions: !!python/tuple
- 32
- 32
- 3
learning_rate: 0.001
number_workers: 1
adversary: False
label_dict:
  0: airplane
  1: automobile
  2: bird
  3: cat
  4: deer
  5: dog
  6: frog
  7: horse
  8: ship
  9: truck
