dataset_directory: '/home/dylan/datasets/cifar_png/'
output_directory: '/tmp/'
model_file: null
model_name: 'classifier'
number_epochs: 20
batch_size: 32
input_dimensions: !!python/tuple
- 32
- 32
- 3
learning_rate: 0.001
number_workers: 1
adversary: False
